CREATE DATABASE Mercado;

USE Mercado;

CREATE TABLE Tb_Saldos
(
	PRODUTO VARCHAR (10),
	SALDO_INICIAL NUMERIC(10),
	SALDO_FINAL NUMERIC(10),
	DATA_ULTIMA_MOV DATETIME
);

CREATE TABLE tb_Vendas
(
	ID_VENDAS INT,
	PRODUTO VARCHAR(10),
	QUANTIDADE INT,
	DATA DATETIME
);

CREATE SEQUENCE SEQ_TV_VENDAS
	AS NUMERIC
	START WITH 1
	INCREMENT BY 1;

CREATE TABLE TB_HISTORICO_VENDAS
(
	PRODUTO VARCHAR(10),
	QUANTIDADE INT,
	DATA_VENAS DATETIME
);

INSERT INTO Tb_Saldos VALUES ('PRODUTO A', 0 , 100,GETDATE());

SELECT * FROM Tb_Saldos;

-- TRIGGER DE ATUALIZAÇÃO DE SALDOS

DROP TRIGGER trg_ajustaSaldo;
GO
CREATE TRIGGER trg_ajustaSaldo
ON TB_VENDAS
FOR INSERT
AS 
	BEGIN
		DECLARE @QUANTIDADE INT,
				@DATA DATETIME,
				@PRODUTO VARCHAR(10)
		SELECT @DATA = DATA, @QUANTIDADE = QUANTIDADE, @PRODUTO = PRODUTO
		FROM inserted
		
		UPDATE Tb_Saldos
		SET SALDO_FINAL = SALDO_FINAL - @QUANTIDADE, DATA_ULTIMA_MOV = @DATA
		WHERE PRODUTO = @PRODUTO;

		INSERT INTO TB_HISTORICO_VENDAS (PRODUTO, QUANTIDADE, DATA_VENAS)
		VALUES (@PRODUTO, @QUANTIDADE, @DATA)

	END
GO

-- FORAM VENDIDAS 2 UNIDADES DO PRODUTO A

INSERT INTO tb_Vendas (ID_VENDAS, PRODUTO, QUANTIDADE, DATA)
VALUES (NEXT VALUE FOR seq_tv_vendas, 'PRODUTO A' , 5, GETDATE());

SELECT * FROM tb_Vendas;
SELECT * FROM Tb_Saldos;
SELECT * FROM TB_HISTORICO_VENDAS;






