--PRIEMIRO TRIGGER COM AFTER
CREATE TRIGGER tgr_primeiro_trigeer
ON dbo.Editora
AFTER INSERT
AS
PRINT 'OLA TRIGGER';

--INSERINDO UM VALOR PARA ATIVAÇÃO DO TRIGGER 
INSERT INTO Editora (nome) VALUES ('EDITORA DO JUCA');

--DELETAR TRIGGER
DROP TRIGGER valida_editora_existente;
  
  CREATE TRIGGER valida_editora_existente
ON dbo.Editora
INSTEAD OF INSERT 
AS
	BEGIN
		DECLARE @NOME VARCHAR(100);
		SELECT @NOME = NOME FROM inserted;
		IF(EXISTS(SELECT * FROM DBO.Editora WHERE nome LIKE (@NOME)))
			BEGIN
				PRINT 'A EDITORA ' + @NOME + ' JA EXISTE';
			END
		ELSE
			
			BEGIN
				INSERT INTO Editora (nome) VALUES (@NOME);
				PRINT 'A EDITORA ' + @NOME + ' SALVA';
			END
		END

INSERT INTO Editora (nome) VALUES ('JUCA12345');

INSERT INTO Editora (nome) VALUES ('EDITORA BERNADO INTREPARISTE ');

SELECT * FROM editora;

INSERT INTO Editora (nome) VALUES ('EDITORA DO VITOR POZZEBOM');